[package]
name = "squirrel-lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "1"
tokio = { version = "1", features = [
    "macros",
    "rt-multi-thread",
    "sync",
    "io-std",
] }
tower-lsp = "0.20"
tree-sitter = "0.20"
tree-sitter-squirrel = "1.0"
